### ISSUE TITLE
victoria.sh - does it need instructions or awareness of user's current git branch?

### ISSUE THREAD

**Issue by pryme** [ProgrammingRobotsStudyGroup/robo_magellan#1]
Question stemming from weak git knowledge: victoria.sh does `git pull` to update. If the user's current branch is `master` then I think this is ok. If user's current branch is `my_branch` does the desired action happen? My understanding is that `git pull` in that scenario will pull the changes from the tracked remote branch, so master would not be updated?

**Comment by merose** [comment]
Removed the shell script because it was no longer used, so this issue is moot. Will close.
