### ISSUE TITLE
Upgrade Pixhawk from Rover 3.1.2 to 3.2+

### ISSUE THREAD

**Issue by jeremyolsen** [ProgrammingRobotsStudyGroup/robo_magellan#29]
Potential issues and needed testing after upgrade:

1) Ultrasonic configuration: Fred has a successful implementation on version 3.2.0
2) EKF2 enabled:  parameters may have changed from reading prior documents
3) Reverse steering issues
4) GUIDED mode working
5) Various speed issues encountered with AUTO mode

**Comment by merose** [comment]
As part of #3, probably need to check PWM steering limits again, just in case there is interaction with the new Pixhawk code.

**Comment by jeremyolsen** [comment]
Upgrade complete to 3.2.3 and all of the params reloaded.  No errors and everything seems to be normal so far.  The output from pixhawk looks much cleaner too.
Ultrasonics - working
EKF2 - no param changes necessary
(Rest of the testing will have to occur off the stand tomorrow.)

**Comment by jeremyolsen** [comment]
More testing...
1) Intermediate waypoint fix is working.  Able to test in the stand showing a cone to the camera and hitting the touch to get it to stop with a single waypoint.
2) Guided mode - Working!  However is giving extra feedback in the console and isn't working as smootly as using manual/throttle
3) Steering - still needs to be reversed for throttle/manual for some reason.  Seems like it's not working correctly when using GUIDED.
4) Speed - haven't fully tested it, but not sure if I am seeing issues or not.  Speed is lowered, but not noticeable when I drop values.

**Comment by jeremyolsen** [comment]
Closing this as a reasonable amount of testing has been performed and the upgrade doesn't seem to have introduced any noticeable regressions.  Individual issues can be opened up if any are found.
