### ISSUE TITLE
Determine how best to go into reverse and back up

### ISSUE THREAD

**Issue by merose** [ProgrammingRobotsStudyGroup/robo_magellan#31]
Need to determine the best way to go into reverse and back up.

**Comment by jeremyolsen** [comment]
Tested and verified using a suggestion of a 'reverse pump' with the ESC.
https://diydrones.com/group/ardurover-user-group/forum/topics/how-should-we-handle-reverse-in-ardurover?commentId=705844%3AComment%3A1042762&groupId=705844%3AGroup%3A903163

**Comment by jeremyolsen** [comment]
Currently implementing and testing the reverse pump in the navigator code.

**Comment by jeremyolsen** [comment]
Closing
