### ISSUE TITLE
Examine video from 04-20 to determine minimum cone area for good cone detection

### ISSUE THREAD

**Issue by merose** [ProgrammingRobotsStudyGroup/robo_magellan#39]
Several runs which were otherwise successful required executing the recover turn at one or more cones. It's possible that decreasing the minimum cone area will help the robot spot the cone earlier, to better handle GPS drift. The video from 04-20 should be examined to determine what the minimum cone area should be.

Testing on 04-20 used either 400 pixels or 350 pixels as the minimum cone area.

**Comment by jeremyolsen** [comment]
Here are the 4.19 videos - https://drive.google.com/open?id=15tMdN9OMkXJGFfAKV19_WGj8m0biE3R6

**Comment by jeremyolsen** [comment]
I'm going to do a test in the morning to determine the distance to the cone when it is first seen based upon the minimum cone area.

**Comment by merose** [comment]
Based on April 20th videos, the cone never had a Y value greater than about 240, about halfway up. However, the terrain was smoother, so there was less bouncing of the front-end. Using a Y threshold of 280-300 should be ample.
