### ISSUE TITLE
No messages published to /mavros/mission/current

### ISSUE THREAD

**Issue by javatechs** [ProgrammingRobotsStudyGroup/robo_magellan#5]
In state_follow_waypoint.py, subscriber of /mavros/mission/current doesn't see any messages even though current wp changes announced in a ROS log.

**Comment by merose** [comment]
The correct topic is /mavros/mission/reached, I think, so this may be corrected by either editing state_follow_waypoint.py or by remapping.

**Comment by merose** [comment]
Fixed code in uav_control.py. Will close.
